### ISSUE TITLE
Is there a minimum DLL change to support Modern Chrome?

### ISSUE THREAD

**Issue by ghostplant** [Skulltrail192/One-Core-Api-Source#69]
Since some libraries are buggy and have translation problem, I'd like to have least DLL upgraded to make Chrome work, while minimizing the possibility for other traditional apps fail to run.

**Comment by jonm58** [comment]
> Since some libraries are buggy and have translation problem, I'd like to have least DLL upgraded to make Chrome work, while minimizing the possibility for other traditional apps fail to run.

you can use supermium

**Comment by jonm58** [comment]
@Skulltrail192 Close this issue
